on:
  schedule:
    - cron: '18 14 * * *'
  workflow_dispatch:

jobs:
  echedulet-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Informações do Schecule
        run: echo "O Schedule é executado diariamente às 14:12 UTC (11:12 BRT)."
        
      - name: Relatório diário automatizado
        run: echo "Gerando relatório diário automatizado..."  