name: Issue Trigger Workflow

permissions:
  issues: write

on:
  issues:
    types: [opened, edited, closed]

jobs:
  issue-job:
    runs-on: ubuntu-latest
    steps:
      - name: Issue opened
        if: github.event.action == 'opened'
        run: 'echo "Issue opened: #${{ github.event.issue.number }} - ${{ github.event.issue.title }}"'

      - name: Issue edited
        if: github.event.action == 'edited'
        run: 'echo "Issue edited: #${{ github.event.issue.number }} - ${{ github.event.issue.title }}"'

      - name: Issue closed
        if: github.event.action == 'closed'
        run: 'echo "Issue closed: #${{ github.event.issue.number }} - ${{ github.event.issue.title }}"'